import type { Project, ChecklistItem, ComplianceResult, CategoryScore, ComplianceIssue } from "@/types";

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "กระทรวงดิจิทัล - Portal Website",
    description: "เว็บพอร์ทัลสำหรับบริการดิจิทัลภาครัฐ",
    status: "in_progress",
    score: 78,
    checklistCount: 24,
    passedCount: 18,
    failedCount: 4,
    reviewCount: 2,
    createdAt: "2024-01-15",
    updatedAt: "2024-01-18",
    torFileName: "tor-digital-ministry.pdf",
    category: "Government Portal",
  },
  {
    id: "2",
    name: "สำนักงานประกันสังคม - ระบบบริการออนไลน์",
    description: "ระบบให้บริการออนไลน์สำหรับผู้ประกันตน",
    status: "completed",
    score: 92,
    checklistCount: 31,
    passedCount: 28,
    failedCount: 2,
    reviewCount: 1,
    createdAt: "2024-01-10",
    updatedAt: "2024-01-12",
    torFileName: "tor-sso-online.pdf",
    uiFileName: "sso-screenshot.png",
    category: "Social Security",
  },
  {
    id: "3",
    name: "กรมสรรพากร - E-Filing System",
    description: "ระบบยื่นแบบภาษีออนไลน์สำหรับประชาชน",
    status: "pending",
    score: 0,
    checklistCount: 0,
    passedCount: 0,
    failedCount: 0,
    reviewCount: 0,
    createdAt: "2024-01-20",
    category: "Tax System",
  },
  {
    id: "4",
    name: "กรมการปกครอง - ระบบทะเบียนราษฎร์",
    description: "ระบบบริการทะเบียนราษฎร์ออนไลน์",
    status: "completed",
    score: 85,
    checklistCount: 28,
    passedCount: 24,
    failedCount: 3,
    reviewCount: 1,
    createdAt: "2024-01-08",
    updatedAt: "2024-01-11",
    torFileName: "tor-dopa.pdf",
    uiFileName: "dopa-ui.png",
    category: "Civil Registration",
  },
  {
    id: "5",
    name: "กระทรวงสาธารณสุข - Health Portal",
    description: "พอร์ทัลสุขภาพสำหรับประชาชนและบุคลากรทางการแพทย์",
    status: "in_progress",
    score: 61,
    checklistCount: 18,
    passedCount: 11,
    failedCount: 5,
    reviewCount: 2,
    createdAt: "2024-01-18",
    updatedAt: "2024-01-19",
    torFileName: "tor-moph.pdf",
    category: "Healthcare",
  },
];

export const mockChecklist: ChecklistItem[] = [
  {
    id: "wcag-1.1.1",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Non-text Content",
    description: "All non-text content that is presented to the user has a text alternative that serves the equivalent purpose.",
    required: true,
    status: "pass",
    severity: "critical",
    wcagLevel: "A",
    suggestion: "Ensure all images have meaningful alt text that describes the content.",
  },
  {
    id: "wcag-1.4.3",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Contrast (Minimum)",
    description: "The visual presentation of text and images of text has a contrast ratio of at least 4.5:1.",
    required: true,
    status: "fail",
    severity: "critical",
    wcagLevel: "AA",
    suggestion: "Increase the contrast ratio of body text from 3.2:1 to at least 4.5:1. Consider using #333333 instead of #888888 for secondary text.",
  },
  {
    id: "wcag-1.4.4",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Resize Text",
    description: "Text can be resized without assistive technology up to 200 percent without loss of content or functionality.",
    required: true,
    status: "pass",
    severity: "major",
    wcagLevel: "AA",
  },
  {
    id: "wcag-2.1.1",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Keyboard",
    description: "All functionality of the content is operable through a keyboard interface.",
    required: true,
    status: "pass",
    severity: "critical",
    wcagLevel: "A",
  },
  {
    id: "wcag-2.4.3",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Focus Order",
    description: "If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operation.",
    required: true,
    status: "review",
    severity: "major",
    wcagLevel: "A",
    suggestion: "Review the tab order in the main navigation and form sections to ensure logical flow.",
  },
  {
    id: "wcag-2.4.7",
    category: "Accessibility",
    standard: "WCAG 2.1",
    title: "Focus Visible",
    description: "Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.",
    required: true,
    status: "fail",
    severity: "critical",
    wcagLevel: "AA",
    suggestion: "Add visible focus styles (outline or border) to all interactive elements. Remove `outline: none` from CSS.",
  },
  {
    id: "twcag-1.1",
    category: "Accessibility",
    standard: "TWCAG 2010",
    title: "ข้อความทางเลือกสำหรับภาพ",
    description: "ภาพทุกภาพต้องมีข้อความทางเลือก (alt text) ที่สื่อความหมายอย่างเหมาะสม",
    required: true,
    status: "pass",
    severity: "critical",
    suggestion: "ตรวจสอบให้แน่ใจว่าภาพประกอบทั้งหมดมี alt text ที่สื่อความหมาย",
  },
  {
    id: "twcag-1.2",
    category: "Accessibility",
    standard: "TWCAG 2010",
    title: "เนื้อหาเสียงและวิดีโอ",
    description: "เนื้อหาเสียงและวิดีโอต้องมีคำบรรยายหรือข้อความถอดเสียง",
    required: false,
    status: "pending",
    severity: "major",
  },
  {
    id: "policy-1",
    category: "Policy",
    standard: "Website Policy",
    title: "นโยบายความเป็นส่วนตัว",
    description: "เว็บไซต์ต้องแสดงนโยบายความเป็นส่วนตัวที่ชัดเจน ครบถ้วน และเข้าถึงได้ง่าย",
    required: true,
    status: "review",
    severity: "major",
    suggestion: "ตรวจสอบว่านโยบายความเป็นส่วนตัวครอบคลุมข้อกำหนด PDPA และสามารถเข้าถึงได้จากทุกหน้า",
  },
  {
    id: "policy-2",
    category: "Policy",
    standard: "Website Policy",
    title: "เงื่อนไขการใช้งาน",
    description: "เว็บไซต์ต้องมีเงื่อนไขการใช้งานที่ชัดเจนและครบถ้วน",
    required: true,
    status: "pass",
    severity: "minor",
  },
  {
    id: "policy-3",
    category: "Policy",
    standard: "PDPA",
    title: "การเก็บรวบรวมข้อมูลส่วนบุคคล",
    description: "การเก็บรวบรวม ใช้ หรือเปิดเผยข้อมูลส่วนบุคคลต้องได้รับความยินยอมจากเจ้าของข้อมูล",
    required: true,
    status: "pass",
    severity: "critical",
  },
  {
    id: "policy-4",
    category: "Policy",
    standard: "Website Policy",
    title: "แผนผังเว็บไซต์ (Sitemap)",
    description: "เว็บไซต์ต้องมี Sitemap ที่ครบถ้วนและอัปเดตอยู่เสมอ",
    required: false,
    status: "pass",
    severity: "info",
  },
  {
    id: "tech-1",
    category: "Technical",
    standard: "Website Policy",
    title: "HTTPS Protocol",
    description: "เว็บไซต์ต้องใช้ HTTPS สำหรับการสื่อสารทั้งหมดเพื่อความปลอดภัยของข้อมูล",
    required: true,
    status: "pass",
    severity: "critical",
  },
  {
    id: "tech-2",
    category: "Technical",
    standard: "Website Policy",
    title: "Mobile Responsive Design",
    description: "เว็บไซต์ต้องแสดงผลได้อย่างถูกต้องบนอุปกรณ์มือถือและแท็บเล็ต",
    required: true,
    status: "pass",
    severity: "major",
  },
  {
    id: "tech-3",
    category: "Technical",
    standard: "Performance",
    title: "Page Load Performance",
    description: "หน้าเว็บต้องโหลดเสร็จภายใน 3 วินาทีบนการเชื่อมต่อ 4G",
    required: true,
    status: "fail",
    severity: "major",
    suggestion: "บีบอัดรูปภาพและใช้ lazy loading เพื่อลดเวลาการโหลดหน้าเว็บ",
  },
  {
    id: "tech-4",
    category: "Technical",
    standard: "Security",
    title: "Content Security Policy",
    description: "เว็บไซต์ต้องมีการตั้งค่า Content Security Policy (CSP) ที่เหมาะสม",
    required: true,
    status: "review",
    severity: "major",
    suggestion: "เพิ่ม CSP header เพื่อป้องกัน XSS attacks",
  },
  {
    id: "content-1",
    category: "Content",
    standard: "Website Policy",
    title: "ภาษาที่ชัดเจนและเข้าใจง่าย",
    description: "เนื้อหาต้องเขียนด้วยภาษาที่ชัดเจน เข้าใจง่าย เหมาะสมกับกลุ่มเป้าหมาย",
    required: true,
    status: "pass",
    severity: "major",
  },
  {
    id: "content-2",
    category: "Content",
    standard: "Website Policy",
    title: "ข้อมูลติดต่อ",
    description: "เว็บไซต์ต้องแสดงข้อมูลติดต่อที่ชัดเจน รวมถึงที่อยู่ อีเมล และเบอร์โทรศัพท์",
    required: true,
    status: "pass",
    severity: "minor",
  },
  {
    id: "content-3",
    category: "Content",
    standard: "Website Policy",
    title: "วันที่อัปเดตเนื้อหา",
    description: "เนื้อหาสำคัญต้องแสดงวันที่อัปเดตล่าสุดอย่างชัดเจน",
    required: false,
    status: "fail",
    severity: "minor",
    suggestion: "เพิ่มวันที่อัปเดตล่าสุดในส่วนเนื้อหาสำคัญ",
  },
];

export const mockComplianceResult: ComplianceResult = {
  projectId: "1",
  overallScore: 78,
  analyzedAt: "2024-01-18T10:30:00Z",
  summary: {
    total: 24,
    passed: 18,
    failed: 4,
    review: 2,
  },
  categoryScores: [
    { category: "Accessibility", score: 71, passed: 5, failed: 2, review: 1, total: 8 },
    { category: "Policy", score: 88, passed: 4, failed: 0, review: 1, total: 5 },
    { category: "Technical", score: 75, passed: 3, failed: 1, review: 1, total: 5 },
    { category: "Content", score: 83, passed: 2, failed: 1, review: 0, total: 3 },
  ] as CategoryScore[],
  issues: [
    {
      id: "issue-1",
      checklistItemId: "wcag-1.4.3",
      title: "ค่า Contrast ของข้อความต่ำกว่ามาตรฐาน",
      description: "ข้อความในส่วน secondary content มีค่า contrast ratio เพียง 3.2:1 ซึ่งต่ำกว่าข้อกำหนด WCAG 2.1 ที่ต้องการ 4.5:1",
      severity: "critical",
      suggestion: "เปลี่ยนสีข้อความ secondary จาก #888888 เป็น #595959 หรือเข้มกว่า เพื่อให้ได้ค่า contrast ratio 4.5:1",
      category: "Accessibility",
      standard: "WCAG 2.1 (AA)",
      element: ".secondary-text, .helper-text",
    },
    {
      id: "issue-2",
      checklistItemId: "wcag-2.4.7",
      title: "ไม่มี Focus Indicator สำหรับ Keyboard Navigation",
      description: "องค์ประกอบ interactive ทั้งหมดถูกลบ outline focus ออก ทำให้ผู้ใช้ที่ใช้ keyboard ไม่สามารถมองเห็นตำแหน่งปัจจุบันได้",
      severity: "critical",
      suggestion: "เพิ่ม CSS focus styles ให้กับทุก interactive element: `*:focus { outline: 2px solid #166EA8; outline-offset: 2px; }`",
      category: "Accessibility",
      standard: "WCAG 2.1 (AA)",
      element: "a, button, input, select, textarea",
    },
    {
      id: "issue-3",
      checklistItemId: "tech-3",
      title: "เวลาโหลดหน้าเว็บนานเกินไป",
      description: "หน้าแรกใช้เวลาโหลด 5.2 วินาที ซึ่งเกินกว่าข้อกำหนด 3 วินาที",
      severity: "major",
      suggestion: "บีบอัดรูปภาพให้ใช้ WebP format, ใช้ lazy loading สำหรับรูปภาพ, และ minify JavaScript/CSS",
      category: "Technical",
      standard: "Performance Standard",
      element: "img, script, link",
    },
    {
      id: "issue-4",
      checklistItemId: "content-3",
      title: "ไม่แสดงวันที่อัปเดตเนื้อหา",
      description: "หน้าข่าวสารและประกาศไม่มีการแสดงวันที่อัปเดตล่าสุด",
      severity: "minor",
      suggestion: "เพิ่มแท็ก <time> ที่แสดงวันที่อัปเดตล่าสุดในทุกบทความข่าวและประกาศ",
      category: "Content",
      standard: "Website Policy",
      element: ".news-article, .announcement",
    },
  ] as ComplianceIssue[],
  checklist: mockChecklist,
};

export const mockDashboardStats = {
  totalProjects: 5,
  checklistsAnalyzed: 12,
  avgComplianceScore: 79,
  reportsGenerated: 8,
};
